### PR TITLE
Feature/es module

### PR DESCRIPTION
**Pull request by rowanc1**
Takes over #7

### CODE REVIEW

**Comment by rowanc1** [comment]
There is still a bug on the install. I will try @paulirwin's suggestion of putting the tsconfig back into the source and see if webpack behaves.

**Comment by rowanc1** [comment]
Ok, I think this should work when we deploy it now, added the draft PR idea from #7 to put the tsconfig in the src directory, and figured out how to make that work with webpack.

**Comment by paulirwin** [comment]
Looks good to me! 🚀

**Comment by rowanc1** [comment]
Nice! Thanks again for your PR! :)

**Comment by rowanc1** [comment]
Released as 0.3.1!

**Comment by paulirwin** [comment]
Confirmed that this resolves the Angular build warning. Thank you!

**Pull request merged**
